// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSQaS5H8Xn0OjsgibChEnr3iuZUpErTA',
    appId: '1:894832029175:web:0ef568360eed61674f52f2',
    messagingSenderId: '894832029175',
    projectId: 'meddetect-b9e38',
    authDomain: 'meddetect-b9e38.firebaseapp.com',
    storageBucket: 'meddetect-b9e38.appspot.com',
    measurementId: 'G-KPG793T5WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTdRo2i-d32w6of18xoWE4i-wEXZm4_I',
    appId: '1:894832029175:android:0bea4d64c26cdb4a4f52f2',
    messagingSenderId: '894832029175',
    projectId: 'meddetect-b9e38',
    storageBucket: 'meddetect-b9e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjzP40rHMcPUmfSmGDPPGA7-3XP1bdoM',
    appId: '1:894832029175:ios:084c892ce7cff50c4f52f2',
    messagingSenderId: '894832029175',
    projectId: 'meddetect-b9e38',
    storageBucket: 'meddetect-b9e38.appspot.com',
    iosBundleId: 'com.example.meddetectApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNjzP40rHMcPUmfSmGDPPGA7-3XP1bdoM',
    appId: '1:894832029175:ios:4e068c33ddb0037d4f52f2',
    messagingSenderId: '894832029175',
    projectId: 'meddetect-b9e38',
    storageBucket: 'meddetect-b9e38.appspot.com',
    iosBundleId: 'com.example.meddetectApplication.RunnerTests',
  );
}
