# Generated by Django 5.0.2 on 2024-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('White', 'White'), ('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Maroon', 'Maroon'), ('Orange', 'Orange'), ('Peach', 'Peach'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Tan', 'Tan'), ('Yellow', 'Yellow'), ('Beige & Red', 'Beige & Red'), ('Black & Green', 'Black & Green'), ('Black & Teal', 'Black & Teal'), ('Black & Yellow', 'Black & Yellow'), ('Blue & Brown', 'Blue & Brown'), ('Blue & Gray', 'Blue & Gray'), ('Blue & Green', 'Blue & Green'), ('Blue & Orange', 'Blue & Orange'), ('Blue & Peach', 'Blue & Peach'), ('Blue & Pink', 'Blue & Pink'), ('Blue & White', 'Blue & White'), ('Blue & White Specks', 'Blue & White Specks'), ('Blue & Yellow', 'Blue & Yellow'), ('Brown & Clear', 'Brown & Clear'), ('Brown & Orange', 'Brown & Orange'), ('Brown & Peach', 'Brown & Peach'), ('Brown & Red', 'Brown & Red'), ('Brown & White', 'Brown & White'), ('Brown & Yellow', 'Brown & Yellow'), ('Clear & Green', 'Clear & Green'), ('Dark & Light Green', 'Dark & Light Green'), ('Gold & White', 'Gold & White'), ('Gray & Peach', 'Gray & Peach'), ('Gray & Pink', 'Gray & Pink'), ('Gray & Red', 'Gray & Red'), ('Gray & White', 'Gray & White'), ('Gray & Yellow', 'Gray & Yellow'), ('Green & Orange', 'Green & Orange'), ('Green & Peach', 'Green & Peach'), ('Green & Pink', 'Green & Pink'), ('Green & Purple', 'Green & Purple'), ('Green & Turquoise', 'Green & Turquoise'), ('Green & White', 'Green & White'), ('Green & Yellow', 'Green & Yellow'), ('Lavender & White', 'Lavender & White'), ('Maroon & Pink', 'Maroon & Pink'), ('Orange & Turquoise', 'Orange & Turquoise'), ('Orange & White', 'Orange & White'), ('Orange & Yellow', 'Orange & Yellow'), ('Peach & Purple', 'Peach & Purple'), ('Peach & Red', 'Peach & Red'), ('Peach & White', 'Peach & White'), ('Pink & Purple', 'Pink & Purple'), ('Pink & Red Specks', 'Pink & Red Specks'), ('Pink & Turquoise', 'Pink & Turquoise'), ('Pink & White', 'Pink & White'), ('Pink & Yellow', 'Pink & Yellow'), ('Red & Turquoise', 'Red & Turquoise'), ('Red & White', 'Red & White'), ('Red & Yellow', 'Red & Yellow'), ('Tan & White', 'Tan & White'), ('Turquoise & White', 'Turquoise & White'), ('Turquoise & Yellow', 'Turquoise & Yellow'), ('White & Blue Specks', 'White & Blue Specks'), ('White & Red Specks', 'White & Red Specks'), ('White & Yellow', 'White & Yellow'), ('Yellow & Gray', 'Yellow & Gray'), ('Yellow & White', 'Yellow & White')], max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('imprint', models.CharField(max_length=255)),
                ('shape', models.CharField(choices=[('Barrel', 'Barrel'), ('Capsule/Oblong', 'Capsule/Oblong'), ('Character-shape', 'Character-shape'), ('Egg-shape', 'Egg-shape'), ('Eight-sided', 'Eight-sided'), ('Oval', 'Oval'), ('Figure eight-shape', 'Figure eight-shape'), ('Five-sided', 'Five-sided'), ('Four-sided', 'Four-sided'), ('Gear-shape', 'Gear-shape'), ('Heart-shape', 'Heart-shape'), ('Kidney-shape', 'Kidney-shape'), ('Rectangle', 'Rectangle'), ('Round', 'Round'), ('Seven-sided', 'Seven-sided'), ('Six-sided', 'Six-sided'), ('Three-sided', 'Three-sided'), ('U-shape', 'U-shape')], max_length=255)),
            ],
        ),
    ]
