# Generated by Django 5.0.4 on 2024-04-08 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('White', 'White'), ('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Maroon', 'Maroon'), ('Orange', 'Orange'), ('Peach', 'Peach'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Tan', 'Tan'), ('Yellow', 'Yellow'), ('Beige & Red', 'Beige & Red'), ('Black & Green', 'Black & Green'), ('Black & Teal', 'Black & Teal'), ('Black & Yellow', 'Black & Yellow'), ('Blue & Brown', 'Blue & Brown'), ('Blue & Gray', 'Blue & Gray'), ('Blue & Green', 'Blue & Green'), ('Blue & Orange', 'Blue & Orange'), ('Blue & Peach', 'Blue & Peach'), ('Blue & Pink', 'Blue & Pink'), ('Blue & White', 'Blue & White'), ('Blue & White Specks', 'Blue & White Specks'), ('Blue & Yellow', 'Blue & Yellow'), ('Brown & Clear', 'Brown & Clear'), ('Brown & Orange', 'Brown & Orange'), ('Brown & Peach', 'Brown & Peach'), ('Brown & Red', 'Brown & Red'), ('Brown & White', 'Brown & White'), ('Brown & Yellow', 'Brown & Yellow'), ('Clear & Green', 'Clear & Green'), ('Dark & Light Green', 'Dark & Light Green'), ('Gold & White', 'Gold & White'), ('Gray & Peach', 'Gray & Peach'), ('Gray & Pink', 'Gray & Pink'), ('Gray & Red', 'Gray & Red'), ('Gray & White', 'Gray & White'), ('Gray & Yellow', 'Gray & Yellow'), ('Green & Orange', 'Green & Orange'), ('Green & Peach', 'Green & Peach'), ('Green & Pink', 'Green & Pink'), ('Green & Purple', 'Green & Purple'), ('Green & Turquoise', 'Green & Turquoise'), ('Green & White', 'Green & White'), ('Green & Yellow', 'Green & Yellow'), ('Lavender & White', 'Lavender & White'), ('Maroon & Pink', 'Maroon & Pink'), ('Orange & Turquoise', 'Orange & Turquoise'), ('Orange & White', 'Orange & White'), ('Orange & Yellow', 'Orange & Yellow'), ('Peach & Purple', 'Peach & Purple'), ('Peach & Red', 'Peach & Red'), ('Peach & White', 'Peach & White'), ('Pink & Purple', 'Pink & Purple'), ('Pink & Red Specks', 'Pink & Red Specks'), ('Pink & Turquoise', 'Pink & Turquoise'), ('Pink & White', 'Pink & White'), ('Pink & Yellow', 'Pink & Yellow'), ('Red & Turquoise', 'Red & Turquoise'), ('Red & White', 'Red & White'), ('Red & Yellow', 'Red & Yellow'), ('Tan & White', 'Tan & White'), ('Turquoise & White', 'Turquoise & White'), ('Turquoise & Yellow', 'Turquoise & Yellow'), ('White & Blue Specks', 'White & Blue Specks'), ('White & Red Specks', 'White & Red Specks'), ('White & Yellow', 'White & Yellow'), ('Yellow & Gray', 'Yellow & Gray'), ('Yellow & White', 'Yellow & White')], max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('imprint', models.CharField(max_length=255)),
                ('shape', models.CharField(choices=[('Barrel', 'Barrel'), ('Capsule/Oblong', 'Capsule/Oblong'), ('Character-shape', 'Character-shape'), ('Egg-shape', 'Egg-shape'), ('Eight-sided', 'Eight-sided'), ('Oval', 'Oval'), ('Figure eight-shape', 'Figure eight-shape'), ('Five-sided', 'Five-sided'), ('Four-sided', 'Four-sided'), ('Gear-shape', 'Gear-shape'), ('Heart-shape', 'Heart-shape'), ('Kidney-shape', 'Kidney-shape'), ('Rectangle', 'Rectangle'), ('Round', 'Round'), ('Seven-sided', 'Seven-sided'), ('Six-sided', 'Six-sided'), ('Three-sided', 'Three-sided'), ('U-shape', 'U-shape')], max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('size', models.SmallIntegerField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=255)),
                ('side_effects', models.CharField(blank=True, max_length=255)),
                ('prescription', models.BooleanField(default=False)),
                ('drug_class', models.CharField(blank=True, max_length=255)),
                ('pregnancy', models.CharField(blank=True, max_length=255)),
                ('CSA_schedule', models.CharField(blank=True, max_length=255)),
                ('labeler_supplier', models.CharField(blank=True, max_length=255)),
                ('national_drug_code', models.CharField(blank=True, max_length=255)),
                ('inactive_ingredients', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('dose', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pill_vault.pill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PillIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_hours', models.IntegerField(help_text='Frequency of intake in hours. E.g., 24 for daily.', null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of pills taken at each intake.', null=True)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='pill_vault.pill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pill_intakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField(help_text='Time to remind user to take the pill.')),
                ('active', models.BooleanField(default=True, help_text='Whether the reminder is active.')),
                ('pill_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pill_vault.pillintake')),
            ],
        ),
        migrations.CreateModel(
            name='PillScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side', models.CharField(max_length=255)),
                ('back_side', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.ManyToManyField(related_name='search_history', to='pill_vault.pill')),
            ],
        ),
        migrations.CreateModel(
            name='UserScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scans', to='pill_vault.pillscanhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
