# Generated by Django 5.0.4 on 2024-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pill',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
