# Generated by Django 5.0.4 on 2024-04-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0002_pill_image_pill_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='application',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='pill',
            name='purpose',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='pill',
            name='side_effects',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
