# Generated by Django 5.0.2 on 2024-03-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0003_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
