# Generated by Django 5.0.4 on 2024-04-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0003_pill_application_alter_pill_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='application',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
