# Generated by Django 5.0.2 on 2024-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0004_remove_user_email_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
