# Generated by Django 5.0.2 on 2024-03-04 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0005_user_email_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='pillintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pill_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pillhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pillintake',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pillintake',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='pillintake',
            name='frequency',
            field=models.CharField(default='', help_text="Frequency of intake, e.g., 'daily', 'twice a day', etc.", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pillintake',
            name='pill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='pill_vault.pill'),
        ),
        migrations.AlterField(
            model_name='pillintake',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity of pills taken at each intake.'),
        ),
        migrations.CreateModel(
            name='PillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField(help_text='Time to remind user to take the pill.')),
                ('active', models.BooleanField(default=True, help_text='Whether the reminder is active.')),
                ('pill_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pill_vault.pillintake')),
            ],
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
