# Generated by Django 5.0.2 on 2024-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0006_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillintake',
            name='frequency_hours',
            field=models.IntegerField(help_text='Frequency of intake in hours. E.g., 24 for daily.'),
            preserve_default=False,
        ),
    ]
