# Generated by Django 5.0.2 on 2024-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0007_remove_pillintake_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillintake',
            name='intake_time',
        ),
        migrations.AlterField(
            model_name='pillintake',
            name='frequency_hours',
            field=models.IntegerField(help_text='Frequency of intake in hours. E.g., 24 for daily.', null=True),
        ),
        migrations.AlterField(
            model_name='pillintake',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity of pills taken at each intake.', null=True),
        ),
    ]
