# Generated by Django 5.0.3 on 2024-03-26 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0009_pillscanhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillscanhistory',
            name='user',
        ),
        migrations.CreateModel(
            name='UserScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scans', to='pill_vault.pillscanhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
