# Generated by Django 5.0.4 on 2024-04-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_vault', '0010_userscanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='CSA_schedule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='drug_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='inactive_ingredients',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='labeler_supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='national_drug_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='pregnancy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pill',
            name='side_effects',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pill',
            name='size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='symptoms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
